name: deploy
on:
  push:
    branches:
      - develop
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup environment
        if: endsWith(github.ref, 'develop')
        run: echo ::set-env name=DOMAIN_NAME::dev.${{ secrets.SITE_DOMAIN }}
      - run: echo ${DOMAIN_NAME}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          SITE_DOMAIN: ${DOMAIN_NAME}

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install aws-cli
        run: pip install awscli --upgrade
      - name: Deploy to s3
        run: aws s3 sync --exact-timestamps --delete dist/ s3://${DOMAIN_NAME}
      - name: Clear cloudfront cache
        run:  aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'
        env:
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
